# bundle exec jekyll serve
exclude: ["Rakefile"]
highlighter: rouge

title : "DesignSafe-CI"
author :
  name : TACC DesignSafe Team
  email : announce@designsafe-ci.org
  github : DesignSafe-CI

production_url : https://designsafe-ci.github.io/api-user-guide/
markdown: kramdown

JB :
  version : 0.3.0
  BASE_PATH : https://designsafe-ci.github.io/api-user-guide/
  archive_path: nil
  categories_path : nil
  tags_path : nil
  atom_path : nil
  rss_path : nil
  comments :
    provider : false
  analytics :
    provider : false
  sharing :
    provider : false
